### ISSUE TITLE
Demo - combobox not linked to SquarePicker

### ISSUE THREAD

**Issue by tonyhallett** [PixiEditor/ColorPicker#24]
In addition there are some redundant Grid attached properties on controls in the first cell ( Border ).

**Comment by Equbuxu** [comment]
The combobox is linked via the code behind, I've done it this way because I wanted to keep the demo simple and avoid creating converters. It's just there to show that you can change the color space, so I think for demo purposes that's good enough.

For the properties, I'll remove them in #23

**Comment by tonyhallett** [comment]
My apologies.
