### ISSUE TITLE
HSL L slider gradient unlike others - does not represent the affect of L

### ISSUE THREAD

**Issue by tonyhallett** [PixiEditor/ColorPicker#26]
When the sliders for RGB / HSV and HSL H and S are moved to a new position the selected colour is the same as that under the thumb.

Given
![image](https://user-images.githubusercontent.com/11292998/152142656-2e014f2d-dae2-4325-bd8d-4ce6d06c23d9.png)

![image](https://user-images.githubusercontent.com/11292998/152142698-216ade2e-333c-4997-83ae-fe56ddfc49b9.png)

![image](https://user-images.githubusercontent.com/11292998/152142773-b593fe5a-b4ba-4ada-b891-ad2535a5b82b.png)

L has two gradient stops - black and white.
![image](https://user-images.githubusercontent.com/11292998/152142845-b28eb03b-b74d-4a3a-8a37-f8143cba174f.png)

By increasing the gradient stops HSL L reflects the effect of moving the L slider on the resulting colour.
I have used 255 equally spaced stops.

![image](https://user-images.githubusercontent.com/11292998/152143224-e57215f7-3edf-480c-a19c-0f51b8a09f3c.png)

New code required in here
https://github.com/PixiEditor/ColorPicker/blob/67151d55baac32123e7d02f2ea723ad8d83eb99f/src/ColorPicker/UIExtensions/HslColorSlider.cs#L21

I used
```
            if (SliderHslType == "L")
            {
                var colorStart = GetColorForSelectedArgb(0);
                var colorEnd = GetColorForSelectedArgb(255);
                LeftCapColor.Color = colorStart;
                RightCapColor.Color = colorEnd;
                var backgroundGradient = new GradientStopCollection();
                
                var numStops = 255;
                for (var i = 0; i < numStops; i++)
                {
                    var ratio = (double)i / numStops;
                    var value = 255 * ratio;
                    backgroundGradient.Add(new GradientStop(GetColorForSelectedArgb((int)value), ratio));
                }
                BackgroundGradient = backgroundGradient;
                return;
            }
```

**Comment by Equbuxu** [comment]
Good catch, fixing this in #23. Using just one additional GradientStop in the middle is enough for an accurate result, so I'm skipping the loop

**Comment by tonyhallett** [comment]
> Using just one additional GradientStop in the middle is enough for an accurate result, so I'm skipping the loop

I didn't have time to do any Maths.
