### ISSUE TITLE
Drop support for out-of-support .NET runtimes (.NET 4.5.2 (support 4.6.2), .NET Core 3.1 and .NET 5)

### ISSUE THREAD

**Issue by Styxxy** [PixiEditor/ColorPicker#41]
Drop support for out-of-support (end-of-life) .NET runtime version. In this case:
* .NET Framework 4.5.2 (target 4.6.2 for now, it will be supported till 2027)
* .NET Core 3.1
* .NET 5

![image](https://github.com/PixiEditor/ColorPicker/assets/1635825/c5bce5b5-b1e0-44f0-94bf-304947e4fd87)

![image](https://github.com/PixiEditor/ColorPicker/assets/1635825/853ddfe8-858c-4ffc-8a9e-2986f383bc53)

See also: 
* https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework
* https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/
* https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core

**Comment by flabbet** [comment]
Technically, supporting these doesn't really require any work from us and I can imagine that some apps might still use .NET 5 or .NET Framework. Unless something in these frameworks doesn't work and requires manual fixes from us, why drop it?

**Comment by Styxxy** [comment]
If someone targets an (out-of-support) framework, they can use an older version of the package.

Why support? Build images will have the old (out-of-support) tooling removed. Why still want to support and maintain out-of-support (with potential security issues) in the code base? Contributors are also required now to install out-dated/not-supported tooling on machines. My personal opinion is that libraries should strive to align on supported frameworks, and drop support for out-dated frameworks. (If someone is "stuck" on older frameworks, they can still use older versions of the library.)

Just my 2 cents.

**Comment by flabbet** [comment]
After longer discussion, we decided not to drop support for these frameworks yet. Having broader range of use cases is our way to go.
