### ISSUE TITLE
Output of Scalar values (ScR, ScG, ScB...) is non-linear?

### ISSUE THREAD

**Issue by ividyon** [PixiEditor/ColorPicker#44]
A simple example:

![2023-11-30_13-36-49__RainbowStoneMVVM](https://github.com/PixiEditor/ColorPicker/assets/1077140/5d6a4cd1-5e64-4d2d-a8b1-571258dd97fe)

A picked color of hex:
- 255
- 215
- 128
- 255

return Scalar values of
- 1
- 0.679
- 0.215
- 1

when you'd expect it to return (float / 255), therefore:
- 1
- 0.84
- 0.5
- 1

I am using SelectedColor to bind a PortableColorPicker to a color.

Some code examples:

```csharp
public Color SelectedColor
    {
        get => _selectedColor;
        set
        {
            OnPropertyChanging();
            _selectedColor = value;
            X = value.ScR;
            Y = value.ScG;
            Z = value.ScB;
            W = value.ScA;
            OnPropertyChanged();
        }
    }

    public float X
    {
        get => Value.X;
        set
        {
            if (Value.X.Equals(value) && _selectedColor.ScR.Equals(value)) return;
            OnPropertyChanging();
            OnPropertyChanging(nameof(SelectedColor));
            Value = Value with { X = value };
            _selectedColor.ScR = value;
            OnPropertyChanged();
            OnPropertyChanged(nameof(SelectedColor));
        }
    }
```

I don't think anything in my code is causing this.

**Comment by flabbet** [comment]
Seems like you are using wrong color space. `ScR`, `ScG`, `ScB` values are part of `System.Windows.Media`, which is part of .NET. According to Microsoft, this Color struct is composed of synchronized ScRgb values (IEC 61966-2-2). 

I am not an expert in the field, but according to my reserach `ScR`, `ScG`, `ScB` represent Linear sRGB space, which expresses RGB color space before the application of transfer function (gamma correction).

If you go to https://ajalt.github.io/colormath/converter/ and input hex colors you provided (255, 215, 128), you'll get the values you expected in sRGB (0-1), when you scroll down to Linear sRGB, you'll see the values you got from  `ScR`, `ScG`, `ScB` properties. sRGB (0-255) and sRGB (0-1) are the same color spaces, but the latter is normalized, however Linear sRGB is a different color space.

Color Picker operates and displays gamma corrected sRGB, but you are accessing Linear sRGB (without gamma correction) values. 

I suggest calculating normalized values with formula you provided `(value / 255)` where `value` is in range (0-255).
